server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: categoria-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1

        - id: producto-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1
